project_id = "tbofkvyezmpovoezjyyl"

[functions.zapier-notifications]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.validate-family-code]
verify_jwt = false

[functions.plaid-link-token]
verify_jwt = true

[functions.plaid-exchange-token]
verify_jwt = true