project_id = "tbofkvyezmpovoezjyyl"

[functions.create-user-with-credentials]
verify_jwt = true

[functions.zapier-notifications]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.validate-family-code]
verify_jwt = false

[functions.plaid-link-token]
verify_jwt = true

[functions.plaid-exchange-token]
verify_jwt = true

[functions.plaid-refresh-accounts]
verify_jwt = true

[functions.notify-message-email]
verify_jwt = false

[functions.notify-meeting-creation]
verify_jwt = false

[functions.send-mass-notification]
verify_jwt = true

[functions.process-payment-reminders]
verify_jwt = false

[functions.chatgpt-support]
verify_jwt = true

[functions.ai-family-tree-assistant]
verify_jwt = true

[functions.send-gohighlevel-email]
verify_jwt = true

[functions.send-meeting-reminders]
verify_jwt = false

[functions.check-trust-access]
verify_jwt = false

[functions.generate-trust-document]
verify_jwt = false

[functions.send-trust-email]
verify_jwt = false

[functions.fetch-trust-sheets]
verify_jwt = false